---
# Gentoo tasks file for vctLabs.local-package-repo

- name: create dir for repo config
  file:
    name: /etc/portage/repos.conf
    state: directory
    mode: 0755

- name: configure package repo 
  template: 
    dest: /etc/portage/repos.conf/local-packages.conf
    src: gentoo/local-packages.conf.j2
    mode: 0644

- name: install local packages
  portage: 
    name: "{{item}}"
    state: present
    #update: yes
  with_items:
    - "{{package_list}}"

