---
# RedHat tasks file for vctLabs.local-package-repo

- name: install repo tool
  yum:
    name: createrepo
    state: present

- name: generate repo metadata
  command: "/usr/bin/createrepo -v {{dest_basedir}}/{{installable_subdir}}"
    
- name: configure package repo
  template: 
    dest: /etc/yum.repos.d/local-packages.repo
    src: redhat/local-packages.repo.j2
    mode: 0644

- name: install local packages
  yum: 
    name: "{{item}}"
    state: latest
    update_cache: yes
  with_items:
    - "{{package_list}}"

